---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{env "APPNAME"}}
  namespace: {{env "REPONAME"}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{env "APPNAME"}}
  minReplicas: {{env "MINREPLICAS"}}
  maxReplicas: {{env "MAXREPLICAS"}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
